# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='account.proto',
  package='Cell',
  serialized_pb='\n\raccount.proto\x12\x04\x43\x65ll\x1a\x11\x63ommon_data.proto\"x\n\x14GetUserProfileReqMsg\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\x15\n\rsession_token\x18\x02 \x01(\t\x12+\n\x0cusr_prf_type\x18\x03 \x01(\x0e\x32\x15.Cell.UserProfileType\x12\x0f\n\x07org_uid\x18\x04 \x01(\r\"\xb6\x02\n\x15GetUserProfileRespMsg\x12\x1f\n\x08ret_code\x18\x01 \x02(\x0e\x32\r.Cell.RetCode\x12\r\n\x05phone\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x1c\n\x06gender\x18\x04 \x01(\x0e\x32\x0c.Cell.Gender\x12\x10\n\x08\x62irthday\x18\x05 \x01(\t\x12\x11\n\tavada_url\x18\x06 \x01(\t\x12\x10\n\x08usr_name\x18\x07 \x01(\t\x12\x12\n\navada_size\x18\x08 \x01(\t\x12#\n\nblood_type\x18\t \x01(\x0e\x32\x0f.Cell.BloodType\x12.\n\rconstellation\x18\n \x01(\x0e\x32\x17.Cell.ConstellationType\x12 \n\x06zodiac\x18\x0b \x01(\x0e\x32\x10.Cell.ZodiacType\"\x8d\x02\n\x15GetUserAchieveRespMsg\x12\x1f\n\x08ret_code\x18\x01 \x02(\x0e\x32\r.Cell.RetCode\x12\x16\n\x0e\x63reate_ugc_num\x18\x02 \x01(\r\x12\x14\n\x0cpost_ugc_num\x18\x03 \x01(\r\x12\x14\n\x0cpass_ugc_num\x18\x04 \x01(\r\x12\x17\n\x0ftotal_post_dist\x18\x05 \x01(\r\x12\x15\n\rmax_post_dist\x18\x06 \x01(\r\x12\x14\n\x0cugc_seed_num\x18\x07 \x01(\r\x12\x0f\n\x07pk_coin\x18\x08 \x01(\x03\x12\x12\n\npk_win_num\x18\t \x01(\r\x12\x13\n\x0bpk_lose_num\x18\n \x01(\r\x12\x0f\n\x07pk_rank\x18\x0b \x01(\r\"s\n\x14SetUserProfileReqMsg\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\x15\n\rsession_token\x18\x02 \x01(\t\x12\x11\n\tavada_url\x18\x03 \x01(\t\x12\x10\n\x08usr_name\x18\x04 \x01(\t\x12\x12\n\navada_size\x18\x05 \x01(\t\"8\n\x15SetUserProfileRespMsg\x12\x1f\n\x08ret_code\x18\x01 \x02(\x0e\x32\r.Cell.RetCode')




_GETUSERPROFILEREQMSG = descriptor.Descriptor(
  name='GetUserProfileReqMsg',
  full_name='Cell.GetUserProfileReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uid', full_name='Cell.GetUserProfileReqMsg.uid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='session_token', full_name='Cell.GetUserProfileReqMsg.session_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='usr_prf_type', full_name='Cell.GetUserProfileReqMsg.usr_prf_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='org_uid', full_name='Cell.GetUserProfileReqMsg.org_uid', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=162,
)


_GETUSERPROFILERESPMSG = descriptor.Descriptor(
  name='GetUserProfileRespMsg',
  full_name='Cell.GetUserProfileRespMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='Cell.GetUserProfileRespMsg.ret_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='phone', full_name='Cell.GetUserProfileRespMsg.phone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='email', full_name='Cell.GetUserProfileRespMsg.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gender', full_name='Cell.GetUserProfileRespMsg.gender', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='birthday', full_name='Cell.GetUserProfileRespMsg.birthday', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='avada_url', full_name='Cell.GetUserProfileRespMsg.avada_url', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='usr_name', full_name='Cell.GetUserProfileRespMsg.usr_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='avada_size', full_name='Cell.GetUserProfileRespMsg.avada_size', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blood_type', full_name='Cell.GetUserProfileRespMsg.blood_type', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='constellation', full_name='Cell.GetUserProfileRespMsg.constellation', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='zodiac', full_name='Cell.GetUserProfileRespMsg.zodiac', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=165,
  serialized_end=475,
)


_GETUSERACHIEVERESPMSG = descriptor.Descriptor(
  name='GetUserAchieveRespMsg',
  full_name='Cell.GetUserAchieveRespMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='Cell.GetUserAchieveRespMsg.ret_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='create_ugc_num', full_name='Cell.GetUserAchieveRespMsg.create_ugc_num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='post_ugc_num', full_name='Cell.GetUserAchieveRespMsg.post_ugc_num', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pass_ugc_num', full_name='Cell.GetUserAchieveRespMsg.pass_ugc_num', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='total_post_dist', full_name='Cell.GetUserAchieveRespMsg.total_post_dist', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_post_dist', full_name='Cell.GetUserAchieveRespMsg.max_post_dist', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ugc_seed_num', full_name='Cell.GetUserAchieveRespMsg.ugc_seed_num', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pk_coin', full_name='Cell.GetUserAchieveRespMsg.pk_coin', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pk_win_num', full_name='Cell.GetUserAchieveRespMsg.pk_win_num', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pk_lose_num', full_name='Cell.GetUserAchieveRespMsg.pk_lose_num', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pk_rank', full_name='Cell.GetUserAchieveRespMsg.pk_rank', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=478,
  serialized_end=747,
)


_SETUSERPROFILEREQMSG = descriptor.Descriptor(
  name='SetUserProfileReqMsg',
  full_name='Cell.SetUserProfileReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uid', full_name='Cell.SetUserProfileReqMsg.uid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='session_token', full_name='Cell.SetUserProfileReqMsg.session_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='avada_url', full_name='Cell.SetUserProfileReqMsg.avada_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='usr_name', full_name='Cell.SetUserProfileReqMsg.usr_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='avada_size', full_name='Cell.SetUserProfileReqMsg.avada_size', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=749,
  serialized_end=864,
)


_SETUSERPROFILERESPMSG = descriptor.Descriptor(
  name='SetUserProfileRespMsg',
  full_name='Cell.SetUserProfileRespMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='Cell.SetUserProfileRespMsg.ret_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=866,
  serialized_end=922,
)

import common_data_pb2

_GETUSERPROFILEREQMSG.fields_by_name['usr_prf_type'].enum_type = common_data_pb2._USERPROFILETYPE
_GETUSERPROFILERESPMSG.fields_by_name['ret_code'].enum_type = common_data_pb2._RETCODE
_GETUSERPROFILERESPMSG.fields_by_name['gender'].enum_type = common_data_pb2._GENDER
_GETUSERPROFILERESPMSG.fields_by_name['blood_type'].enum_type = common_data_pb2._BLOODTYPE
_GETUSERPROFILERESPMSG.fields_by_name['constellation'].enum_type = common_data_pb2._CONSTELLATIONTYPE
_GETUSERPROFILERESPMSG.fields_by_name['zodiac'].enum_type = common_data_pb2._ZODIACTYPE
_GETUSERACHIEVERESPMSG.fields_by_name['ret_code'].enum_type = common_data_pb2._RETCODE
_SETUSERPROFILERESPMSG.fields_by_name['ret_code'].enum_type = common_data_pb2._RETCODE

class GetUserProfileReqMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETUSERPROFILEREQMSG
  
  # @@protoc_insertion_point(class_scope:Cell.GetUserProfileReqMsg)

class GetUserProfileRespMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETUSERPROFILERESPMSG
  
  # @@protoc_insertion_point(class_scope:Cell.GetUserProfileRespMsg)

class GetUserAchieveRespMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETUSERACHIEVERESPMSG
  
  # @@protoc_insertion_point(class_scope:Cell.GetUserAchieveRespMsg)

class SetUserProfileReqMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETUSERPROFILEREQMSG
  
  # @@protoc_insertion_point(class_scope:Cell.SetUserProfileReqMsg)

class SetUserProfileRespMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETUSERPROFILERESPMSG
  
  # @@protoc_insertion_point(class_scope:Cell.SetUserProfileRespMsg)

# @@protoc_insertion_point(module_scope)
