# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='initial.proto',
  package='Cell',
  serialized_pb='\n\rinitial.proto\x12\x04\x43\x65ll\x1a\x11\x63ommon_data.proto\"\xfc\x02\n\tRegReqMsg\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x0b\n\x03uid\x18\x02 \x01(\r\x12\r\n\x05phone\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x1c\n\x06gender\x18\x05 \x01(\x0e\x32\x0c.Cell.Gender\x12\x10\n\x08\x62irthday\x18\x06 \x01(\t\x12\x11\n\tavada_url\x18\x07 \x01(\t\x12\x10\n\x08usr_name\x18\x08 \x01(\t\x12\x10\n\x08password\x18\t \x01(\t\x12#\n\nreg_source\x18\n \x01(\x0e\x32\x0f.Cell.RegSource\x12\x12\n\navada_size\x18\x0b \x01(\t\x12#\n\nblood_type\x18\x0c \x01(\x0e\x32\x0f.Cell.BloodType\x12.\n\rconstellation\x18\r \x01(\x0e\x32\x17.Cell.ConstellationType\x12 \n\x06zodiac\x18\x0e \x01(\x0e\x32\x10.Cell.ZodiacType\x12\x16\n\x03geo\x18\x0f \x01(\x0b\x32\t.Cell.Geo\"P\n\nRegRespMsg\x12\x1f\n\x08ret_code\x18\x01 \x02(\x0e\x32\r.Cell.RetCode\x12!\n\tuser_stat\x18\x02 \x01(\x0e\x32\x0e.Cell.UserStat\"I\n\x0bLoginReqMsg\x12\x10\n\x08usr_info\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x16\n\x03geo\x18\x03 \x01(\x0b\x32\t.Cell.Geo\"v\n\x0cLoginRespMsg\x12\x1f\n\x08ret_code\x18\x01 \x02(\x0e\x32\r.Cell.RetCode\x12\x0b\n\x03uid\x18\x02 \x01(\r\x12\x15\n\rsession_token\x18\x03 \x01(\t\x12!\n\tuser_stat\x18\x04 \x01(\x0e\x32\x0e.Cell.UserStat\"h\n\nInitReqMsg\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12%\n\x0b\x64\x65vice_type\x18\x02 \x01(\x0e\x32\x10.Cell.DeviceType\x12\x0f\n\x07\x61pp_key\x18\x03 \x01(\t\x12\x0f\n\x07\x61pp_ver\x18\x04 \x01(\t\"u\n\x0bInitRespMsg\x12\x1f\n\x08ret_code\x18\x01 \x02(\x0e\x32\r.Cell.RetCode\x12\x0b\n\x03uid\x18\x02 \x01(\r\x12\x15\n\rsession_token\x18\x03 \x01(\t\x12!\n\tuser_stat\x18\x04 \x01(\x0e\x32\x0e.Cell.UserStat\"&\n\x12\x43heckUserRegReqMsg\x12\x10\n\x08usr_info\x18\x01 \x01(\t\"Y\n\x13\x43heckUserRegRespMsg\x12\x1f\n\x08ret_code\x18\x01 \x02(\x0e\x32\r.Cell.RetCode\x12!\n\tuser_stat\x18\x02 \x01(\x0e\x32\x0e.Cell.UserStat')




_REGREQMSG = descriptor.Descriptor(
  name='RegReqMsg',
  full_name='Cell.RegReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='session_token', full_name='Cell.RegReqMsg.session_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='uid', full_name='Cell.RegReqMsg.uid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='phone', full_name='Cell.RegReqMsg.phone', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='email', full_name='Cell.RegReqMsg.email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gender', full_name='Cell.RegReqMsg.gender', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='birthday', full_name='Cell.RegReqMsg.birthday', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='avada_url', full_name='Cell.RegReqMsg.avada_url', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='usr_name', full_name='Cell.RegReqMsg.usr_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='Cell.RegReqMsg.password', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reg_source', full_name='Cell.RegReqMsg.reg_source', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='avada_size', full_name='Cell.RegReqMsg.avada_size', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blood_type', full_name='Cell.RegReqMsg.blood_type', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='constellation', full_name='Cell.RegReqMsg.constellation', index=12,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='zodiac', full_name='Cell.RegReqMsg.zodiac', index=13,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='geo', full_name='Cell.RegReqMsg.geo', index=14,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=423,
)


_REGRESPMSG = descriptor.Descriptor(
  name='RegRespMsg',
  full_name='Cell.RegRespMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='Cell.RegRespMsg.ret_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_stat', full_name='Cell.RegRespMsg.user_stat', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=425,
  serialized_end=505,
)


_LOGINREQMSG = descriptor.Descriptor(
  name='LoginReqMsg',
  full_name='Cell.LoginReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='usr_info', full_name='Cell.LoginReqMsg.usr_info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='Cell.LoginReqMsg.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='geo', full_name='Cell.LoginReqMsg.geo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=507,
  serialized_end=580,
)


_LOGINRESPMSG = descriptor.Descriptor(
  name='LoginRespMsg',
  full_name='Cell.LoginRespMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='Cell.LoginRespMsg.ret_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='uid', full_name='Cell.LoginRespMsg.uid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='session_token', full_name='Cell.LoginRespMsg.session_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_stat', full_name='Cell.LoginRespMsg.user_stat', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=582,
  serialized_end=700,
)


_INITREQMSG = descriptor.Descriptor(
  name='InitReqMsg',
  full_name='Cell.InitReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='device_id', full_name='Cell.InitReqMsg.device_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='device_type', full_name='Cell.InitReqMsg.device_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='app_key', full_name='Cell.InitReqMsg.app_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='app_ver', full_name='Cell.InitReqMsg.app_ver', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=702,
  serialized_end=806,
)


_INITRESPMSG = descriptor.Descriptor(
  name='InitRespMsg',
  full_name='Cell.InitRespMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='Cell.InitRespMsg.ret_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='uid', full_name='Cell.InitRespMsg.uid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='session_token', full_name='Cell.InitRespMsg.session_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_stat', full_name='Cell.InitRespMsg.user_stat', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=808,
  serialized_end=925,
)


_CHECKUSERREGREQMSG = descriptor.Descriptor(
  name='CheckUserRegReqMsg',
  full_name='Cell.CheckUserRegReqMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='usr_info', full_name='Cell.CheckUserRegReqMsg.usr_info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=927,
  serialized_end=965,
)


_CHECKUSERREGRESPMSG = descriptor.Descriptor(
  name='CheckUserRegRespMsg',
  full_name='Cell.CheckUserRegRespMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ret_code', full_name='Cell.CheckUserRegRespMsg.ret_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_stat', full_name='Cell.CheckUserRegRespMsg.user_stat', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=967,
  serialized_end=1056,
)

import common_data_pb2

_REGREQMSG.fields_by_name['gender'].enum_type = common_data_pb2._GENDER
_REGREQMSG.fields_by_name['reg_source'].enum_type = common_data_pb2._REGSOURCE
_REGREQMSG.fields_by_name['blood_type'].enum_type = common_data_pb2._BLOODTYPE
_REGREQMSG.fields_by_name['constellation'].enum_type = common_data_pb2._CONSTELLATIONTYPE
_REGREQMSG.fields_by_name['zodiac'].enum_type = common_data_pb2._ZODIACTYPE
_REGREQMSG.fields_by_name['geo'].message_type = common_data_pb2._GEO
_REGRESPMSG.fields_by_name['ret_code'].enum_type = common_data_pb2._RETCODE
_REGRESPMSG.fields_by_name['user_stat'].enum_type = common_data_pb2._USERSTAT
_LOGINREQMSG.fields_by_name['geo'].message_type = common_data_pb2._GEO
_LOGINRESPMSG.fields_by_name['ret_code'].enum_type = common_data_pb2._RETCODE
_LOGINRESPMSG.fields_by_name['user_stat'].enum_type = common_data_pb2._USERSTAT
_INITREQMSG.fields_by_name['device_type'].enum_type = common_data_pb2._DEVICETYPE
_INITRESPMSG.fields_by_name['ret_code'].enum_type = common_data_pb2._RETCODE
_INITRESPMSG.fields_by_name['user_stat'].enum_type = common_data_pb2._USERSTAT
_CHECKUSERREGRESPMSG.fields_by_name['ret_code'].enum_type = common_data_pb2._RETCODE
_CHECKUSERREGRESPMSG.fields_by_name['user_stat'].enum_type = common_data_pb2._USERSTAT

class RegReqMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGREQMSG
  
  # @@protoc_insertion_point(class_scope:Cell.RegReqMsg)

class RegRespMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGRESPMSG
  
  # @@protoc_insertion_point(class_scope:Cell.RegRespMsg)

class LoginReqMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGINREQMSG
  
  # @@protoc_insertion_point(class_scope:Cell.LoginReqMsg)

class LoginRespMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGINRESPMSG
  
  # @@protoc_insertion_point(class_scope:Cell.LoginRespMsg)

class InitReqMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INITREQMSG
  
  # @@protoc_insertion_point(class_scope:Cell.InitReqMsg)

class InitRespMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INITRESPMSG
  
  # @@protoc_insertion_point(class_scope:Cell.InitRespMsg)

class CheckUserRegReqMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHECKUSERREGREQMSG
  
  # @@protoc_insertion_point(class_scope:Cell.CheckUserRegReqMsg)

class CheckUserRegRespMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHECKUSERREGRESPMSG
  
  # @@protoc_insertion_point(class_scope:Cell.CheckUserRegRespMsg)

# @@protoc_insertion_point(module_scope)
